# SUPPORT_OBJS := 

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# START = ./getput-start.o

# uncomment if you want it to automatically run.
RUN=1

PROGS = query-jit.c

include ../../../../libpi/mk/Makefile.robust